# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x10\x64iscordbot.agent\"\x97\x01\n\x0b\x43hatRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08user_tag\x18\x02 \x01(\t\x12\x12\n\nchannel_id\x18\x03 \x01(\t\x12\x10\n\x08guild_id\x18\x04 \x01(\t\x12\x16\n\x0einteraction_id\x18\x05 \x01(\t\x12\x14\n\x0cuser_message\x18\x06 \x01(\t\x12\x11\n\timage_url\x18\x07 \x01(\t\"\xa7\x01\n\x0c\x43hatResponse\x12\x14\n\x0cmessage_text\x18\x01 \x01(\t\x12\x31\n\x06images\x18\x02 \x03(\x0b\x32!.discordbot.agent.ImageAttachment\x12\x33\n\x07summary\x18\x03 \x01(\x0b\x32\".discordbot.agent.ExecutionSummary\x12\x19\n\x11\x66\x61llback_occurred\x18\x04 \x01(\x08\"V\n\x10\x45xecutionSummary\x12\x17\n\x0f\x65xecution_count\x18\x01 \x01(\x05\x12\x12\n\nany_failed\x18\x02 \x01(\x08\x12\x15\n\rexecution_ids\x18\x03 \x03(\t\"D\n\x0fImageAttachment\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x11\n\tmime_type\x18\x03 \x01(\t\"\x0f\n\rHealthRequest\"!\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\"E\n\x0eObserveRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08user_tag\x18\x02 \x01(\t\x12\x10\n\x08question\x18\x03 \x01(\t\"G\n\x0fObserveResponse\x12\x13\n\x0b\x61nswer_text\x18\x01 \x01(\t\x12\x10\n\x08\x64ql_used\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"/\n\rRunDqlRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\"C\n\x0eRunDqlResponse\x12\x11\n\trows_json\x18\x01 \x01(\t\x12\x0f\n\x07\x63olumns\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t2\xb8\x02\n\x05\x41gent\x12\x45\n\x04\x43hat\x12\x1d.discordbot.agent.ChatRequest\x1a\x1e.discordbot.agent.ChatResponse\x12K\n\x06Health\x12\x1f.discordbot.agent.HealthRequest\x1a .discordbot.agent.HealthResponse\x12N\n\x07Observe\x12 .discordbot.agent.ObserveRequest\x1a!.discordbot.agent.ObserveResponse\x12K\n\x06RunDql\x12\x1f.discordbot.agent.RunDqlRequest\x1a .discordbot.agent.RunDqlResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATREQUEST']._serialized_start=34
  _globals['_CHATREQUEST']._serialized_end=185
  _globals['_CHATRESPONSE']._serialized_start=188
  _globals['_CHATRESPONSE']._serialized_end=355
  _globals['_EXECUTIONSUMMARY']._serialized_start=357
  _globals['_EXECUTIONSUMMARY']._serialized_end=443
  _globals['_IMAGEATTACHMENT']._serialized_start=445
  _globals['_IMAGEATTACHMENT']._serialized_end=513
  _globals['_HEALTHREQUEST']._serialized_start=515
  _globals['_HEALTHREQUEST']._serialized_end=530
  _globals['_HEALTHRESPONSE']._serialized_start=532
  _globals['_HEALTHRESPONSE']._serialized_end=565
  _globals['_OBSERVEREQUEST']._serialized_start=567
  _globals['_OBSERVEREQUEST']._serialized_end=636
  _globals['_OBSERVERESPONSE']._serialized_start=638
  _globals['_OBSERVERESPONSE']._serialized_end=709
  _globals['_RUNDQLREQUEST']._serialized_start=711
  _globals['_RUNDQLREQUEST']._serialized_end=758
  _globals['_RUNDQLRESPONSE']._serialized_start=760
  _globals['_RUNDQLRESPONSE']._serialized_end=827
  _globals['_AGENT']._serialized_start=830
  _globals['_AGENT']._serialized_end=1142
# @@protoc_insertion_point(module_scope)
